# Site settings
title: Paul Bastide
email: paul.bastide[at]agroparistech.fr
description: > # this means to ignore newlines until "baseurl:"
  Ph.D. student in statistics
baseurl: '' # /pbastide.github.io # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  pbastide

# Build settings
markdown: redcarpet
highlighter: pygments
