# Site settings
title: Paul Bastide
email: paul.bastide[at]umontpellier.fr
description: > # this means to ignore newlines until "baseurl:"
  Researcher in statistics
baseurl: '' # /pbastide.github.io # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  pbastide

# Build settings
markdown: kramdown # redcarpet
highlighter: rouge # pygments
